### ISSUE TITLE
Fix offline tests in triton-mlir branch

### ISSUE THREAD

**Issue by binarman** [ROCmSoftwarePlatform/triton#82]
Following ctests are broken (3/19):
- [x] 7 - GcnAsmFormatTest.basic #92 
- [x] 8 - GcnAsmFormatTest.complexInstruction #92 
- 10 - TestGcnAsmFormat (aggregation for mentioned tests)

Following lit tests are broken (8/20):
- [x] TRITON :: Conversion/AMDGPU/load_store.mlir #106 
- [x] TRITON :: Conversion/tritongpu_to_llvm.mlir #103 (one test is still failing, need some refactoring) #130
- [x] TRITON :: Target/tritongpu_to_amdgcn.mlir #107 
- [x] TRITON :: Target/tritongpu_to_hsaco.mlir #107 #120

**Comment by binarman** [comment]
I am going to work on this issue to get familiar with the project

**Comment by binarman** [comment]
I am going to work on this issue to get familiar with the project

**Comment by binarman** [comment]
Closing, because everything is working
